---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgBp2feDktumUI5vOGGWDjL/sL/TTcGfeR16gM89ttWWzkA80VoVWZOe0oFOwOKoQAm+MDbIVsLRoXpC4NseYmqc/eZ0TRTUJwOtl5qMHdyCE6mhVpUM2V9PJXLCYvCcvWnJz9lOK3bVmpDoNoOeS/sXGsq3GKS4qh7KPo3Yqy37tj0w6gfv0Fv0ImUhgJXt0yhnlMPzf6XpmxNcQY6VCvLfN6bpj1a8g+VpjL/H6E8LdCKr4+EpOeIja/d/KTVdlniuyHq9ZlFtntLrup42zdR6xsSaLlA39o+J5CfZOcDcTfGjYau1mNrSxOi1KziyI0JzMHKHKy4Wop1mpz8tdrgY4GHqtcHwFDMrSfFe1Au0BIsPSrrDwK9VSNlOd1c0pDsSmbIDq7QN2lLmw5gz2d7KHTkzwq9j6zmev4yGKeGwAs/Xr0961KB6nSoBz3Ny/FdlL2VvndErOLqpsIpXqaE3yJOKwZEn2cSek5ybK7sJtTOrV0b/DKd28HHeXL+y23C8A+K/DYJoqfTAX8X+Afd9YZCyl3BOcI6GEJUSp6jFtQdH6ZiyqvOVnJBpIruIsQUWsVYqewVnsABxhmjRSQZBPU+A/2r1FD8V5Iig5ZtuyIq9absAjQntMS2bWftkXhQ7/FQxhxqhLFxlwrGzdaS2SiSqOQNCs2UjhLMfGboOvuhcOAoM01Upgbt/Oj3mZ6Efs1R1MMnX6Jp/ZDSnmyiIT1VgrvDRxSpnJnsK5MRWtQ==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
    type: Opaque
