---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-credentials
  namespace: argocd
spec:
  encryptedData:
    password: AgAbkmzuhsJv5Np52W7Tgg0IHM/1UG7OKc4XjNS+bx6EYJth9e4MxUxoZ0SPiWtTJCECxcmBwoXWOkqyO3fOuBFb3s3RccGXJK0glcw0Qo9uc0uEfPcsrnicKF+81t4pObmdWeKV2mRd51oi7IWsUNmLPEmDpI4uT0CSynjcv1F98fUFrqdxubRVG4LKDCfba5i0YId8muH2QEyKXyVbxuYtOyTQUADFdR88Evlncn7QqoF2Z6enfn0ruHu31VvOub4K2nVoNpM5fkpb9GxrMoRTwSvERU4pjHoxup3bfpzmlfOU1KJsZwEh12apbR1ro6ImnwlQhv3HJVLAURekna2AoC8i/QIqM8Fi/Y6A651o87ayDwBLbhOWW0vytQdW1LKvJM/zVZztb6/tVNpkZNoRwuJBuJ1vhyVwt+gzzUkIu92rDz1hded007utBxUwhe3UCrXV1WNF3uFQ8TjMIpkI1Ea1cniU32hThC5WF1WFXcCyoW1ekPrl9ItLl1mhibGIDA5d3s7I3mHOzJEyznmcEJ5n9MDcqbYqJJO2NORPe2hiFZoEeD7Q0NTyK6U3axpkizOm7H350hZVZWQmAzAp4gIvCsbL0oovJML+99X4hwX0mWC7a017gYd+Mx+j3m+x/2Hto8ykhY2DzJi3Ri4w+00UO1HFjguf7sI3KQzp0HFl6Ep7lHrdiMdNSDGGZBXoEBL1yUDf+6Z93SGU75570j5bfwZiWeAq66AcGjl4ePFlGdMnKlKS
    username: AgBqsO10shmjOWHQWNBHVy3jJ53vvj2dEtGQq2ulvnkNSzWYQtqBOMtS5vQM7W+6BkyhAgbXIVX4Y3u9z8W6jivay3MBrAZBQaoVNUmtnO+s9qTki0HabLs1pHkP/vYV8oI4X6mKNQxnPELY50BwoR47+ovwnUC3rDhbhJLVwCnj/4ublAbUiiRqf1O4hpkCMorwU0rZ8Z1+VotuEYtyygtDJJx7hgvnRZqK1ubZyQ20bAStzsX77zdgEzbhHhR07WeHsel9kUY0AHmcf/hxaGgMxJdB8hF13IfT8qg2tbj8lrrqJcqeHc96n8I4aq9Y5TYW4456tAfKPjK1r6YZ+34X3gHvz+aWPHZeOOjND2uhgD6+UNsgmOPbFGrR90HvSpyi69ETpRi92ON5kIk55qY8Yle05OyzjyPD+P9V33UkpMVcSDMSc0QmlFWc0298Cc4W6YP3uk0Q/92oQ1Q/hrLvjlaL+5lr/EwHIwMa/P4kBMlSI4xa4YS2ut1/+o4LHNqbJcykGFawibCghyRKKb8iCzMPbBASJ0se0TULZutT1HRyzrtcGpkcw6LBV9EESX9pX2Hcc/LE1dGOIcFMmof5BR3auL84jSbwCsjsYuJLQoPnyt8l4hEJBzYppepJEJXzA2ZC1M7hUQmp2IhDd5Tf/sJn/6AIOb6+IrWnxExQerdVNHxl1meVqUQrb9EeeJPRIIHLz9QpLKQXIg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-credentials
      namespace: argocd
    type: Opaque
