---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgAUQZa3GeGDAkHiKeWG4dMkp5mZh/ncWAH8qX3cuEtjIB8NwmyhtzQqiFvpVqRoDH89lyIniWJeG3A5sN7pgEDL8eJhjgv+6l7eGKNHdS7PQZH39pDhFmrfmkpdUDMoof1cZcU/kscpce3Uk97k+OGpblOsTkY357fqIP3UycrdAXrCWTKlwQGVoEdmANKIIMRsVk88hyPKcWxuVHliacHPyscZVX1zFAnihGvt9xz6t1XTjmhyTx3aKgJi6fZyCDaqEoTlrWDq9FxF1r9WitbCAKlEUiCfrZXWmyp9YK0YIktMa5u+uc1PxXoXxAUpgneMFYaNa0jFGHVi3WQOUDrFt2ONLKBfMoNbndPZBdxH978xeraytErZ43cuQHDw7Bge84jmrg4WTgG9/+uP9G4CtmdIMhvS4F+PorqFuQIBjBx1PCpBaH4G7bhGZcqRpbPeeRKr+Ix2Hg+i4oOWkBSP1L9+H7cKPQrixFXY9xjz5bXOIVoBYs2VV+W0VaOwox0pN8LYU6X1nLV857+XuenT/C4QjxAPXkihBtQc/hu3Vi6cV5d5isTogJcASmOC6yUGV7hbCdP35upbSA8KVE1Zrn1WMPO3b7pxHwMEYkq+o34/hs3UuK5qCp8PEc2pY67cT/f6aJ5mwYi98Cp6UfHUGpjWc0yY+2cwxiNtH3w0MVwUcXxoGe4gF7qGI3pKfA2EXLaoapR/tqqzrBhZeXync4esNJmO6MeSzTFLJ1hHaA==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
    type: Opaque
