---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCvjatpTmc8hT1LUhd2UuLMev5sO69gvN6FEUsZaab7rl8SAGw0JMdUFw1VMnoMdIxh2Pt4ZGJJgDpwEjvKSAEApfzQCdDbEJrypRetaSM+ZTcssq+Ce40vxB7IsGWm6djm+MkFcmF6H4+rChctPaLC/gwmaFL0gqy1SIXCeyNPQBt8dP+BoilNmQNUISeaiOfQ+WwLddvbVdSwU5YpiMOCbeAvwjbBJFQE9WK1V2MdqW2OagvLVbGRh3ipf5fPziAKnJgK4tCL90kutTMdHSGLRXQ9pjcKaBv2NRt7+uZCThkY0Xx7ijhfQA8LmmwlS2+i6Yh2qH75mevEJF9BRK33ZXAj1CT6ggqd7nBrZK2vMvgN0seWk+UD4hluPddSFsVashUVxkcvgZcgi6maBWbvUm7Se2CJQ4V+2dDK+FqQtNN325CYsQ6xu2FRt8oIJq09tDyjNV7X9fKn2cJhbiB0r3oSBAoy/vfiadhkvmAXsL0VxE091PITuezhlJlrOZIiYyF1FiFcvGZyVjC72aA+ZVjjhwOI4gVC9Q66QDRQ3LbmDZec4oCH7etKw50w3B+5ugLbUBnySLVOZP8gZKTVsFnnPcoJbafYMYHAo7c7mi5/GSu+vxYPWsVTG4te47C3o3gMhH6NWqp/VRQhDwisr7cFt+7mztsC8MkFxGFZ/zf7aHqf791bszfwU+c6QH+kLs/cN+cQPqITNWP6OVENDrKoFmDlABwigIp6WLvx2g==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
    type: Opaque
